//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSync
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbServicesEntities : DbContext
    {
        public DbServicesEntities()
            : base("name=DbServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
        public virtual DbSet<TblCategory> TblCategory { get; set; }
        public virtual DbSet<TblCurrent> TblCurrent { get; set; }
        public virtual DbSet<TblDepartment> TblDepartment { get; set; }
        public virtual DbSet<TblExpense> TblExpense { get; set; }
        public virtual DbSet<TblFaultDetail> TblFaultDetail { get; set; }
        public virtual DbSet<TblInvoiceDetail> TblInvoiceDetail { get; set; }
        public virtual DbSet<TblInvoiceInformation> TblInvoiceInformation { get; set; }
        public virtual DbSet<TblNotes> TblNotes { get; set; }
        public virtual DbSet<TblProduct> TblProduct { get; set; }
        public virtual DbSet<TblProductAcceptance> TblProductAcceptance { get; set; }
        public virtual DbSet<TblProductMovement> TblProductMovement { get; set; }
        public virtual DbSet<TblProductTracking> TblProductTracking { get; set; }
        public virtual DbSet<TblStaff> TblStaff { get; set; }
    }
}
