//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSync
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbServicesEntities : DbContext
    {
        public DbServicesEntities()
            : base("name=DbServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblAARIZADETAY> TblAARIZADETAY { get; set; }
        public virtual DbSet<TblADMIN> TblADMIN { get; set; }
        public virtual DbSet<TbLARACLAR> TbLARACLAR { get; set; }
        public virtual DbSet<TblCARI> TblCARI { get; set; }
        public virtual DbSet<TblDEPARTMAN> TblDEPARTMAN { get; set; }
        public virtual DbSet<TblFATURABILGILERI> TblFATURABILGILERI { get; set; }
        public virtual DbSet<TblFATURADETAY> TblFATURADETAY { get; set; }
        public virtual DbSet<TblGIDER> TblGIDER { get; set; }
        public virtual DbSet<TblKATEGORI> TblKATEGORI { get; set; }
        public virtual DbSet<TblNIOTLAR> TblNIOTLAR { get; set; }
        public virtual DbSet<TblPERSONEL> TblPERSONEL { get; set; }
        public virtual DbSet<TblURUN> TblURUN { get; set; }
        public virtual DbSet<TblURUNHAREKETLERI> TblURUNHAREKETLERI { get; set; }
        public virtual DbSet<TblURUNKABULU> TblURUNKABULU { get; set; }
        public virtual DbSet<TblURUNTAKIBI> TblURUNTAKIBI { get; set; }
    }
}
