//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFaultDetail
    {
        public int FAULTID { get; set; }
        public Nullable<int> PROCESS { get; set; }
        public string PROBLEM { get; set; }
        public string EXPLANATION { get; set; }
        public Nullable<decimal> PREPRICE { get; set; }
        public Nullable<decimal> NETPRICE { get; set; }
        public string PROCESSES { get; set; }
    }
}
