//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGIDER
    {
        public int GIDERID { get; set; }
        public string GIDERACIKLAMASI { get; set; }
        public Nullable<System.DateTime> TARİH { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
    }
}
