//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInvoiceInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblInvoiceInformation()
        {
            this.TblInvoiceDetail = new HashSet<TblInvoiceDetail>();
        }
    
        public int ID { get; set; }
        public string SERIES { get; set; }
        public string SERIESNO { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string HOURS { get; set; }
        public string TAXOFFICE { get; set; }
        public Nullable<int> CURRENT { get; set; }
        public Nullable<short> STAFF { get; set; }
    
        public virtual TblCurrent TblCurrent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblInvoiceDetail> TblInvoiceDetail { get; set; }
        public virtual TblStaff TblStaff { get; set; }
    }
}
