//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInvoiceDetail
    {
        public int INVOICEDETAILID { get; set; }
        public string PRODUCT { get; set; }
        public Nullable<short> NUMBER { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> TOTALAMOUNT { get; set; }
        public Nullable<int> INVOICEID { get; set; }
    
        public virtual TblInvoiceInformation TblInvoiceInformation { get; set; }
    }
}
