//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductAcceptance
    {
        public int PROCESSID { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public Nullable<int> CURRENT { get; set; }
        public Nullable<short> PERSONNEL { get; set; }
        public Nullable<System.DateTime> DATEOFARRIVAL { get; set; }
        public Nullable<System.DateTime> EXITDATE { get; set; }
    
        public virtual TblCurrent TblCurrent { get; set; }
        public virtual TblProduct TblProduct { get; set; }
        public virtual TblStaff TblStaff { get; set; }
    }
}
