//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductMovement
    {
        public int MOVEMENTID { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public Nullable<int> CUSTOMER { get; set; }
        public Nullable<short> STAFF { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<short> NUMBER { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    
        public virtual TblCurrent TblCurrent { get; set; }
        public virtual TblProduct TblProduct { get; set; }
        public virtual TblStaff TblStaff { get; set; }
    }
}
