//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStaff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblStaff()
        {
            this.TblInvoiceInformation = new HashSet<TblInvoiceInformation>();
            this.TblProductAcceptance = new HashSet<TblProductAcceptance>();
            this.TblProductMovement = new HashSet<TblProductMovement>();
        }
    
        public short ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public Nullable<byte> DEPARTMENT { get; set; }
        public string PHOTO { get; set; }
        public string MAIL { get; set; }
        public string TELEPHONE { get; set; }
    
        public virtual TblDepartment TblDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblInvoiceInformation> TblInvoiceInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductAcceptance> TblProductAcceptance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductMovement> TblProductMovement { get; set; }
    }
}
