//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblURUNKABULU
    {
        public int ISLEMID { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> CARI { get; set; }
        public Nullable<short> PERSONEL { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public Nullable<System.DateTime> CIKISTARIHI { get; set; }
    
        public virtual TblCARI TblCARI { get; set; }
        public virtual TblPERSONEL TblPERSONEL { get; set; }
        public virtual TblURUN TblURUN { get; set; }
    }
}
