//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblURUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblURUN()
        {
            this.TblURUNKABULU = new HashSet<TblURUNKABULU>();
            this.TblURUNHAREKETLERI = new HashSet<TblURUNHAREKETLERI>();
            this.TblURUNTAKIBI = new HashSet<TblURUNTAKIBI>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public string MARKA { get; set; }
        public Nullable<decimal> ALISFIYATI { get; set; }
        public Nullable<decimal> SATISFIYATI { get; set; }
        public Nullable<short> STOK { get; set; }
        public Nullable<byte> KATEGORİ { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TblKATEGORI TblKATEGORI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblURUNKABULU> TblURUNKABULU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblURUNHAREKETLERI> TblURUNHAREKETLERI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblURUNTAKIBI> TblURUNTAKIBI { get; set; }
    }
}
